# Build settings

source: .
destination: ./_site
markdown: kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
permalinks: pretty
# safe: true
markdown_ext: md

##############################################################################

# Site settings

name: GINCO Genre Annotation Guidelines
baseurl: "/GINCO-Genre-Annotation-Guidelines"
homeurl: "https://github.com/TajaKuzman/GINCO-Genre-Annotation-Guidelines"
editurl: "https://github.com/TajaKuzman/GINCO-Genre-Annotation-Guidelines/gh-pages"
issueurl: "https://github.com/TajaKuzman/GINCO-Genre-Annotation-Guidelines/issues"

##############################################################################

# Collection settings

collections:
  entity:
    output: true
  relation:
    output: true
  genre_pages:
    output: true
